apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: team-a  # Ensure this namespace exists in your EKS cluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        # Replace the SHA with your actual latest ECR tag from the GitHub Action logs
        image: 731471209315.dkr.ecr.ap-south-1.amazonaws.com/sample-application:3ff39893808dd8e6858f8834881d03f3bce6e3fb
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
